.catalog:
  name: "lease"
  version: "1"
  questions:
    - variable: "registry_url"
      description: "Registry url"
      label: "Registry url"
      type: "string"
      required: true
      default: "registry.viareport.com:8080"
    - variable: "authentication_source"
      description: "Module de verification pour nos services"
      label: "Authentication source"
      type: "service"
      required: true
      default: "authentication/authentication"
lease-front:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
